### ISSUE TITLE
Update Interview training to include CfA code of conduct

### ISSUE THREAD

**Issue by Baleja** [codeforamerica/brigade-playbook#155]
### Overview
We need to review the [reference material](https://github.com/codeforamerica/brigade-playbook/projects/1#card-47125197)
We need to add a code of conduct for interviewers to remain neutral and not lead the conversation. 

### Action Items
- [x] add to the code of conduct page
- [x] Add a slide about questioning and not leading with questions.

### Resources/Instructions
[UXR training](https://docs.google.com/presentation/d/1oDGQvBvippkJg4D_s4ZPKJHXTyoKDLya8VNZv58mDyY/edit#slide=id.g974edb4642_0_0)
[CfA code for Conduct ](https://github.com/codeforamerica/codeofconduct)

**Comment by raquelnish** [comment]
I have updated the Deck with a new Slide for the Code of conduct and a link to Code for America Wiki. The text I added is this:

"The Code for America community expects that Code for America network activities, events, and digital forums a safe and respectful environment for all participants.

Please read our Code of conduct ( this has the link)"

**Comment by MarianneAnthonette** [comment]
Interview Etiquette info has been added to the deck:
#### Be respectful and inclusive
- Learn how to pronounce the name of the person you are interviewing before you start the interview, if possible.
- Use their name, instead of pronouns whenever possible, unless pronouns have been communicated.
- If they mention someone else, please refrain from assuming the gender of the person they mentioned, and use they/them if you are unable to use their name.

#### Creating a comfortable environment
- Do not interrupt the interviewee or make them feel rushed in their answers.
- Showing genuine empathy can help but you must be careful not to adversely affect the interview itself with any of your own responses to the interviewee’s frustrations.

**Comment by ExperimentsInHonesty** [comment]
text for if we find or make this content later
## During the Interview
5. Conducting a structured non-bias interview [conducting an interview]()
