### ISSUE TITLE
Identifying empty ranking number cells in the transcription sheet

### ISSUE THREAD

**Issue by raquelnish** [codeforamerica/brigade-playbook#168]
### Overview

We need a formula in the Transcription Sheet Template that shows a message whenever one the ranking numbers on the questions is blank (usually due to it being zero) so that the UXR will fix it before marking work complete.

### Reason 
Currently, if the UXRs do not pay attention and leave a ranking number cell empty.

### Action Items
- [x] Add a formula to the row B126:
- [x] Test on Training Sheet
- [x] When working add to Template
- [x] Update existing transcription sheets with this formula added to it.

#### Message to use 
If you see this message there is a problem with your sheet. We know what the problem is so click here for instructions on how to fix it.

#### When to display the message
There is an empty column B cell where the 0 is in the row below and needs to be moved up one cell. In order to make the message display any of the defined rows are empty. 12-50 even numbers only.

### Resources/Instructions
 [TRAINING SHEET](https://docs.google.com/spreadsheets/d/1o0SlXYZmQxXxzmLRft7zhd3vvp-NxkX1Ou16qtP2EAs/edit#gid=1321558352)
[Transcription Sheet Template](https://docs.google.com/spreadsheets/d/1SDdReZoN20M_uZ5CaN9y-F4mwqZ5pVkIPsA9AlCtjYs/edit#gid=1976949881)

**Comment by Baleja** [comment]
Reach out to thad to ask him to add the following to the training sheet bottom row B127:
If you see this message there is a problem with your sheet. We know what the problem is so click here for instructions on how to fix it.

**Comment by MarianneAnthonette** [comment]
**Edit**: Changed message to "There is a problem in the sheet! Check column B for an empty grey cell with a 0 or other number(s) in the row below and move the number(s) up into the grey cell."

This takes into account the interviews that have multiple people who have two different rankings.

**Question for @thadk**: Can you think of a better, automated way we can handle the multiple interviewee scenario (since we have to manually duplicate rows to account for Speaker 1 + Speaker 2's individual answers). Also, we aren't even taking into consideration of the interviews that have two different rankings for each person. How should that handled during the transcription verification?

**Comment by thadk** [comment]
Can we just make a quick and dirty manual addendum file of the second-interviewee numerical responses for each question in coordination with the quant team and ignore them otherwise?

**Comment by thadk** [comment]
Can we just make a quick and dirty manual addendum file of the second-interviewee numerical responses for each question in coordination with the quant team and ignore them otherwise? @MarianneAnthonette
