### ISSUE TITLE
Create easy to follow UXR onboarding

### ISSUE THREAD

**Issue by Baleja** [codeforamerica/brigade-playbook#176]
### Overview
We need to create an agile training procedure to get new recruits ready and comfortable to be dropped into the middle of a project. 

### Action Items
- [x] Create document with the learning outcomes and the benefits of UXR. 
- [x] Understand how those benefits relate to this project specifically
- [x] Gage when the documentation will be ready for use and testing. 

Please see our process in the [Process Overview](https://github.com/codeforamerica/brigade-playbook/wiki/Process-overview)

### Resources/Instructions
[ New Transcription Verification Instructions](https://docs.google.com/document/d/1mmwozE1kpQCG3O6eSEO1BSyHeSbX7xeT9pYZZBEl98o/edit#heading=h.spmxg8vntlm1rl)
[Fake Wonder Woman Sheet](https://docs.google.com/spreadsheets/d/1o0SlXYZmQxXxzmLRft7zhd3vvp-NxkX1Ou16qtP2EAs/edit#gid=845721923)
[Understanding columns](https://docs.google.com/document/d/1WDlb7lpDhrS6QGGPIQjzfHUE1tvFI4Ky0drQl-fT01Q/edit#heading=h.8cecuqj0l43c)
[ BOP Extension Project :Transcription Verification Training ](https://docs.google.com/presentation/d/1wuq7am4UW7P4k2wG41yreQUBePwBe47MO60sW1-vm54/edit#slide=id.gbc15626aa8_2_23)

**Comment by Baleja** [comment]
<img width="918" alt="Screenshot 2021-02-22 at 11 56 48" src="https://user-images.githubusercontent.com/75342357/108762602-2589b480-7505-11eb-8274-1f957675e21b.png">

**Comment by xtrementhusiast** [comment]
**Notes about designing the learning experience:**
(Conversation with Andre Plaut of [Human Machine](https://www.ahumanmachine.com/)

We need to separate _SKILLS THEY NEED TO HAVE_ from _EASILY REFERENCED MATERIAL_
Some of this learning can only come from experience. Onboarding won't close the Experience Gap.

**BASIC OUTLINE**

1. Introductions - why did you volunteer? (connect the work to the impact)
2. Introduce the tools
3. Demonstrate the tools
4. Let volunteers apply the tools in a mock session
5. Q&A

**Comment by ExperimentsInHonesty** [comment]
@xtrementhusiast 
**Slide notes from pre instructions part of deck**
- place info you want from participants onto first slide as bullets.
- slide 3 paste the link to the code of conduct in the invitation
- slide 6 cfa goals is too big and it went by too fast
- slide 10 needs better imagery
- slide 12 remove the PA because we don't need to answer it now, but the whole slide would be useful after the training when you are explaining the labeling
- slide 14 - how familiar is your audience with otter.ai
- slide 18 find a picture that is more inclusive body type wise
- slide 28 - make it clear that the people who have done the transcription verification will be the ones offered the Data Organization
- slide 29 please be consistent with how long you are saying it will take

**other notes**
- check all links in incognito window

**Instructions notes**
- use command F and ctrl f to find for the time 
- the spreadsheet is already populated with the questions (comes up when you are showing people the otter.ai and its says 036)
- direct them to video about how to use otter.ai
- page 9 of the instructions has a typo in a screenshot where it says paster instead of paste

**Google Drive:** 
https://drive.google.com/drive/u/0/folders/1Nrd_QaBMdY2oW5UIhGDBO6tLKCiM0f4o
**Roster:**
Roster: https://docs.google.com/spreadsheets/d/158xwYDUfnD8DuRgFfmyhb9c4Bm4V8ac080Ta85egb9A/edit#gid=0

@MarianneAnthonette fixed the conditional formatting

**Comment by ExperimentsInHonesty** [comment]
@xtrementhusiast Here is the bitly for the instructions http://bit.ly/BOP-TV
