### ISSUE TITLE
Schedule UXR Onboarding

### ISSUE THREAD

**Issue by Baleja** [codeforamerica/brigade-playbook#177]
### Overview
We need to schedule agile UXR onboarding to be able to scale our efforts in interview analysis.

### Action Items
- [x] Create an organised UXR training agenda that will ~set people up for self led training~ be used in instructor led training. 
- [x] Add an event to the calendar
- [x] Invite people using messaging in #175 

### Resources/Instructions
[Interview Training Deck](https://docs.google.com/presentation/d/1oDGQvBvippkJg4D_s4ZPKJHXTyoKDLya8VNZv58mDyY/edit#slide=id.g974edb4642_0_0)
[old Transcription training](https://docs.google.com/presentation/d/1wuq7am4UW7P4k2wG41yreQUBePwBe47MO60sW1-vm54/edit#slide=id.g974edb4642_0_0)
Transcription Verification instructions Bitly:  http://bit.ly/BOP-TV
[Transcription Verification Training Deck](https://docs.google.com/presentation/d/1sF_8uE5GWHC5MuCE1oua64KroTABCnINLwnSBCFuZ6Q/edit?usp=sharing)

**Comment by Baleja** [comment]
From issue #74

**Comment by xtrementhusiast** [comment]
Was hoping to schedule UXR/Transcription training this week. Will have to push to week of 3/8...it's taking longer than expected to update the new training deck. @Baleja @MarianneAnthonette @ExperimentsInHonesty

**Comment by ExperimentsInHonesty** [comment]
Notes from another issue that are relvant to this issue

xtrementhusiast commented 27 days ago • 
**Notes about designing the learning experience:**
(Conversation with Andre Plaut of [Human Machine](https://www.ahumanmachine.com/))

We need to separate _SKILLS THEY NEED TO HAVE_ from _EASILY REFERENCED MATERIAL_
Some of this learning can only come from experience. Onboarding won't close the Experience Gap.

**BASIC OUTLINE**

1. Introductions - why did you volunteer? (connect the work to the impact)
2. Introduce the tools
3. Demonstrate the tools
4. Let volunteers apply the tools in a mock session
5. Q&A

**Comment by ExperimentsInHonesty** [comment]
Notes from another issue that are relvant to this issue
ExperimentsInHonesty commented 14 days ago • 
@xtrementhusiast 
**Slide notes from pre instructions part of deck**
- place info you want from participants onto first slide as bullets.
- slide 3 paste the link to the code of conduct in the invitation
- slide 6 cfa goals is too big and it went by too fast
- slide 10 needs better imagery
- slide 12 remove the PA because we don't need to answer it now, but the whole slide would be useful after the training when you are explaining the labeling
- slide 14 - how familiar is your audience with otter.ai
- slide 18 find a picture that is more inclusive body type wise
- slide 28 - make it clear that the people who have done the transcription verification will be the ones offered the Data Organization
- slide 29 please be consistent with how long you are saying it will take

**other notes**
- check all links in incognito window

**Instructions notes**
- use command F and ctrl f to find for the time 
- the spreadsheet is already populated with the questions (comes up when you are showing people the otter.ai and its says 036)
- direct them to video about how to use otter.ai
- page 9 of the instructions has a typo in a screenshot where it says paster instead of paste

**Google Drive:** 
https://drive.google.com/drive/u/0/folders/1Nrd_QaBMdY2oW5UIhGDBO6tLKCiM0f4o
**Roster:**
https://docs.google.com/spreadsheets/d/158xwYDUfnD8DuRgFfmyhb9c4Bm4V8ac080Ta85egb9A/edit#gid=0

@MarianneAnthonette fixed the conditional formatting

**Comment by ExperimentsInHonesty** [comment]
@xtrementhusiast Here is the bitly for the Transcription Verification instructions http://bit.ly/BOP-TV

**Comment by ExperimentsInHonesty** [comment]
The training was conducted 3/17 and additional training (issue assignment) will happen on 3/23
