### ISSUE TITLE
Google Drive

### ISSUE THREAD

**Issue by MasSamH** [codeforamerica/brigade-playbook#29]
### Overview
Resolve google drive access to facilitate quick setup and access to templates.

### Action Items
- [x] Check with Tom on access policy and granting rights

**Comment by ExperimentsInHonesty** [comment]
Here is a copy of the communication I had with Tom about this on August 17th:
Hi @tdooner I am having a challenge with the NAC google drive (which is where I put the BOP documents.  It won’t let me add people to the folder, so I am having to add people to each document which is a major hassle and not sustainable.  So I have two choices
create a bop folder at HackforLA and recreate all the docs (it won’t let me make copies either)
we figure out where at CfA to host the folder so I can add people at the folder level.
Thoughts?

Tom Dooner  9:20 AM
yeah, G Drives are a PITA because of that rule.
My flowchart for working around the problem roughly goes:
Is it an option to just add the people to the entire NAC drive? --> Add them
Is it a small set of documents --> share docs with the people manually
Will it be a large enough number of documents that it warrants its own G Shared Drive with a broader audience? ---> create a new G Shared Drive
If none of these options fit, then make a normal folder in a personal drive, share it with whoever needs it, and then make a shortcut in the shared drive.
If #4 is the best option then I can make the folder for you and transfer its ownership to our system user info@codeforamerica.org, which I think will work well.

**Comment by ExperimentsInHonesty** [comment]
slacked tom asking for # 3 https://cfa.slack.com/archives/G0196272BBN/p1598978336000900
