### ISSUE TITLE
Create new issues for all items in WBS

### ISSUE THREAD

**Issue by MasSamH** [codeforamerica/brigade-playbook#37]
### Overview
We need to create issues so that we stay on track throughout the project

### Action Items
- [x] Review the WBS to double check each item to see whether there is an existing issue
- [ ] Create new issue if not 
- [x] Update the WBS & OKRs doc with issue number

### Resources/Instructions
[BOP Project WBS & OKRs](https://docs.google.com/spreadsheets/d/12SHS1MqdrelWjWf2xjZd9gMeQ6JFI2E9sZ2B3ODZ1bU/edit#gid=30376616)

**Comment by MasSamH** [comment]
@ExperimentsInHonesty @MarianneAnthonette @thadk @raquelnish Here's an update on the: 
[BOP Project WBS & OKRs](https://docs.google.com/spreadsheets/d/12SHS1MqdrelWjWf2xjZd9gMeQ6JFI2E9sZ2B3ODZ1bU/edit?pli=1#gid=30376616) that we went through earlier. Still some unresolved questions. We can discuss hopefully on Thursday.

**Comment by ExperimentsInHonesty** [comment]
pushed off till next tuesday.

**Comment by MasSamH** [comment]
@MasSamH to reconcile the milestones to the OKRs and add any final new issues.

**Comment by MarianneAnthonette** [comment]
@MasSamH Please provide an update

1. Progress
2. Blockers
3. Availability
4. ETA

**Comment by MasSamH** [comment]
Starting to add all new issues on Github with BOP Project WBS/OKR doc. Working through 'In progress' new issues and will then go back into 'prioritised backlog' and then 'ice box' to check we have all current issues in play on the WBS/OKR doc.
Thanks Sam

**Comment by MasSamH** [comment]
@ExperimentsInHonesty @Baleja @MasSamH to meet on WBS/OKR doc.

**Comment by MasSamH** [comment]
@Baleja 
- [ ] Audit the OKR document - does it meet standards?
- [ ] Add OKR label to each issue 
- [ ] Add OKR definitions
- [ ] Any issue marked done but not closed, add note to the comment

**Comment by Baleja** [comment]
Issues that are not closed:

#2 Action item missing "Audit the list and place each link into one of the two categories - based on what is in-development versus in-use"
#51 This issue is addressing the correct milestone labels 
#10 Share successes in your recruitment - address & close as needed. 
#33 These are currently just pictures, is there a better place to put them?
#17 information validation is ongoing
#47 This issue looks complete, close & move to done?
#50 Looks complete but still open, is this ongoing?

**Comment by celeste-hub** [comment]
All issues addressed.
