### ISSUE TITLE
Create HfLA project card for project

### ISSUE THREAD

**Issue by MasSamH** [codeforamerica/brigade-playbook#9]
### Overview
Provide collateral for the Hack for LA website.

### Action Items

- [x] Gather Items
   - [x] 600 x 400 image
      - [x] Alt image text
   - [x] Name of project
   - [x] Blurb about project
   - [x] Links (github, slack channel url, Testing Site, Live Site, etc.)
   - [x] Any resources for a Getting Started link (a link to a wiki, readme(s) or both)
   - [x] What you are looking for skills wise
   - [x] Status: Active
- [x] Add project card 

### Resources/Instructions
See project cards on the hackforla.org website.

**Comment by ethanh256** [comment]
@ExperimentsInHonesty @MasSamH which technologies should be listed?

**Comment by MasSamH** [comment]
@ExperimentsInHonesty 
For Ethan's request, answers to questions 2, 3, and 4. If you have answers to 1, plus any edits to those others below, I can pull together into a response for Ethan. For contributors, we should add Thad too, right? 

Thanks Sam 

2. Which technologies for the project should be listed on the project card?
- GitHub, Google Docs, Google Forms, Calendly, Slack

3. What are Sam and Naomi Chao's Slacks and GitHubs? 

[@Sam H](https://cfa.slack.com/archives/D018ZMNQ9AP)
[Naomi Chao](https://cfa.slack.com/team/U018DSK3231)

What is Sam's last name, or should they just be listed as "Sam?"
Sam H is fine.

4. Bonnie and Naomi's CfA Member I.D.s are listed (UGREE50MT for Bonnie, U018DSK3231 for Naomi) under leadership in Bonnie's comment. Are these supposed to be included in the project card? If so, where?

Yes, please add to the project card. Similar in format to the page [100 automations overview](https://www.hackforla.org/projects/100-automations) 

For BOP Extension Project, we would have:

**Project Leadership**
Co-Product Manager
Bonnie Wolfe CfA Member I.D. UGREE50MT
Co-Product Manager
Sam

**Contributors**
Special Projects Coordinator
Naomi Chao CfA Member I.D U018DSK3231



![image](https://user-images.githubusercontent.com/69813451/91735018-fd4f7780-ebab-11ea-8d02-73865b9e0486.png)


Thanks
Sam

**Comment by MasSamH** [comment]
@ExperimentsInHonesty Member I.Ds. are now added

**Comment by ExperimentsInHonesty** [comment]
ID: 293907049
Name of Project: Civic Tech Structure
Blurb: 
Each of the 80+ Code for America Brigades is an experiment which generates valuable learnings and new effective processes and practices. However, Brigades and other civic tech volunteer organizations need not start from scratch. This project aims to improve existing structures and create new ones that make it easier to share replicable processes and practices so that organizers and members can iterate on each others work, improving outcomes for the whole network.

The Civic Tech Structure first project seeks to improve the the existing Code for America Brigade Organizer’s Playbook (BOP) into a communal, high-value resource for sharing.  We will be performing an intensive UX Research phase with the BOP end users to understand their priorities, infrastructure, and potential contributions.

Links: 
- GitHub  https://github.com/hackforla/civic-tech-structure
- Slack https://hackforla.slack.com/archives/C01A789GTNZ
- Overview https://docs.google.com/document/d/1GkvbJ9byBWBpZklYE6YL5nqa-KbIRz32PnMCeroV_1g/edit?usp=sharing
- [Join UX Team](https://docs.google.com/forms/d/e/1FAIpQLSfJPPz6ASuBVKAvRg0f7WDUuDXVpooqA8rmaDwv-4OUcfrWOw/viewform)
- BOP GitHub https://github.com/codeforamerica/brigade-playbook
- BOP CfA Slack https://cfa.slack.com/archives/G0196272BBN


Status: Active
Partner: Code for America & its Brigades
Location: Remote

Leadership 
- Co-Product Manager
   - Bonnie Wolfe CfA Member I.D. UGREE50MT
- Co-Product Manager 
  - Sam
- Special Projects Coordinator
  - Naomi Chao CfA Member I.D U018DSK3231

Looking for Roles
UI designer (brand building)
UX team manager / Lead
UX researchers (40)

Technologies:
Google Docs (Doc, Sheet, Slide, Forms), HackforLA.org guides

**Comment by KianBadie** [comment]
@ExperimentsInHonesty I edited the project card to be exactly like the most [recent comment](https://github.com/codeforamerica/brigade-playbook/issues/9#issuecomment-689091515) you put in this issue (2 paragraphs for description, wording, correct links) and used earlier comments for when information wasn't there (Ex: Naomi Chao's name for leadership). @MasSamH I also wanted to get a visual confirmation if everything here looks acceptable. 

Like I mentioned earlier, I think the contributors are empty because the repo is not tagged with hack-for-la. In addition, the given BOP CFA slack link was not working for me. It could just be on my end, so check if it works for you. Either way, besides the empty contributors arising from the repo tags and the cfa slack link, this is ready to merge. Just let me know when you would like me to.
![Screenshot from 2020-09-17 15-25-55](https://user-images.githubusercontent.com/18221058/93534863-b5925500-f8fa-11ea-90ba-2bbab7d435a2.png)
![Screenshot from 2020-09-17 15-26-23](https://user-images.githubusercontent.com/18221058/93534868-b6c38200-f8fa-11ea-8e41-9a89ac2ea3dc.png)
![Screenshot from 2020-09-17 15-26-31](https://user-images.githubusercontent.com/18221058/93534870-b75c1880-f8fa-11ea-8d54-79e6bde5b705.png)
![Screenshot from 2020-09-17 15-26-56](https://user-images.githubusercontent.com/18221058/93534873-b75c1880-f8fa-11ea-8f47-fa0d6ff1101a.png)
![Screenshot from 2020-09-17 15-27-04](https://user-images.githubusercontent.com/18221058/93534874-b7f4af00-f8fa-11ea-9b3f-43fb4f3abf66.png)

**Comment by MasSamH** [comment]
Adding another member (Thad) to the team
Add meeting times 

Team Meetings
  - [Saturday](https://us02web.zoom.us/j/89378320605?pwd=NzRjSVd0cGtMQmxqSStWTmdCcGJCZz09) (Add to your Calendar [Google](https://zoom.us/meeting/tZ0ucOGrrDssGtFQdS7UkVkiVAPUDKm2kNRw/ics) - [Outlook](https://zoom.us/meeting/tZ0ucOGrrDssGtFQdS7UkVkiVAPUDKm2kNRw/calendar/google/add))
    - 11am (PDT) 
    - 12noon (MT)
    - 1pm (CDT) 
    - 2pm (EDT) 
    - 8pm (CET) 
  - [Tuesday & Thursdays]( https://us02web.zoom.us/j/82445752258?pwd=TFZMczFxK1hqaEtCdHhoRUtiR3lGUT09) (Add to Calendar [Google](https://zoom.us/meeting/tZYpc-yvqzkoH9yNSwF_xcIZYi4CBgk6VLr4/calendar/google/add) - [Outlook](https://zoom.us/meeting/tZYpc-yvqzkoH9yNSwF_xcIZYi4CBgk6VLr4/ics)
    - 9am (PDT) 
    - 10am (MT)
    - 11am (CDT) 
    - 12pm (EDT) 
    - 6pm (CET)

**Comment by thadk** [comment]
My details:
* Co-Product Manager 
	* Thad Kerosky
	* hackforla.slack.com/team/UAU40G31A

**Comment by KianBadie** [comment]
@MasSamH sorry for getting back to you so late. I was going to add the @thadk this morning, but I noticed the Slack link was not working for me. Does it work for you @MasSamH? This is what I am met with when I visit that url:
![Screenshot from 2020-09-27 09-34-04](https://user-images.githubusercontent.com/18221058/94370397-abafe500-00a4-11eb-80fa-462cd77750d0.png)

**Comment by MasSamH** [comment]
@KianBadie thanks for checking on that Slack link. I also get a loading error. Try this link: [Slack Organizers Playbook](https://cfa.slack.com/archives/C019RCM15FEurl) 
@ExperimentsInHonesty Bonnie, for info and follow up in case I'm offer email during vacation. Thanks Sam

**Comment by KianBadie** [comment]
@MasSamH it looks like that link results in an error too, but it seems like you are linking to the channel you already provided as the BOP CFA slack channel, correct (it looks like there are some extra characters attached to the link you provided `https://cfa.slack.com/archives/C019RCM15FEurl`)? If so, we could add @thadk with the BOP CFA Slack channel as the slack link.

**Comment by MasSamH** [comment]
Thanks Kian. Good spot, my mistake with those extra url’ characters. Okay
to remove them. See if that works?
Thanks Sam

**Comment by KianBadie** [comment]
@MasSamH yes, when removing the extra characters "url" the slack channel now links to the organizers-playbook channel of Code for America :+1:

**Comment by ExperimentsInHonesty** [comment]
Looks good

**Comment by ExperimentsInHonesty** [comment]
https://www.hackforla.org/projects/civic-tech-structure
